import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv
from passlib.context import CryptContext

load_dotenv()
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

async def seed_data():
    client = AsyncIOMotorClient(MONGO_URI)
    db = client.telemedicine
    
    await db.users.delete_many({})
    await db.slots.delete_many({})
    
    admin = {
        "name": "Admin System",
        "email": "admin@gmail.com",
        "password": pwd_context.hash("admin@123"),
        "role": "admin"
    }
    await db.users.insert_one(admin)
    
    doctor = {
        "name": "Dr. AI Specialist",
        "email": "doctor@example.com",
        "password": pwd_context.hash("doctor123"),
        "role": "doctor",
        "specialization": "Cardiology",
        "available_days": "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        "start_time": "09:00",
        "end_time": "17:00",
        "slot_duration": 30,
        "consultation_fee": 500,
        "status": "approved"
    }
    doc_res = await db.users.insert_one(doctor)
    
    # Slots are dynamically generated by the backend now
    
    print("Seed data inserted successfully.")
    client.close()

if __name__ == "__main__":
    asyncio.run(seed_data())
